using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace NBSJ_PICAL
{
    public class C_SIN_PLC_1MIN
    {

        public DateTime TIMESTAMP { get; set; }
        public double SIN_PLC_B01_TE_L_1 { get; set; }
        public double SIN_PLC_B01_TE_L_2 { get; set; }
        public double SIN_PLC_B02_TE_L_1 { get; set; }
        public double SIN_PLC_B02_TE_L_2 { get; set; }
        public double SIN_PLC_B03_TE_L_1 { get; set; }
        public double SIN_PLC_B03_TE_L_2 { get; set; }
        public double SIN_PLC_B04_TE_L_1 { get; set; }
        public double SIN_PLC_B04_TE_L_2 { get; set; }
        public double SIN_PLC_B05_TE_L_1 { get; set; }
        public double SIN_PLC_B05_TE_L_2 { get; set; }
        public double SIN_PLC_B06_TE_L_1 { get; set; }
        public double SIN_PLC_B06_TE_L_2 { get; set; }
        public double SIN_PLC_B07_TE_L_1 { get; set; }
        public double SIN_PLC_B07_TE_L_2 { get; set; }
        public double SIN_PLC_B08_TE_L_1 { get; set; }
        public double SIN_PLC_B08_TE_L_2 { get; set; }
        public double SIN_PLC_B09_TE_L_1 { get; set; }
        public double SIN_PLC_B09_TE_L_2 { get; set; }
        public double SIN_PLC_B10_TE_L_1 { get; set; }
        public double SIN_PLC_B10_TE_L_2 { get; set; }
        public double SIN_PLC_B11_TE_L_1 { get; set; }
        public double SIN_PLC_B11_TE_L_2 { get; set; }
        public double SIN_PLC_B12_TE_L_1 { get; set; }
        public double SIN_PLC_B12_TE_L_2 { get; set; }
        public double SIN_PLC_B13_TE_L_1 { get; set; }
        public double SIN_PLC_B13_TE_L_2 { get; set; }
        public double SIN_PLC_B14_TE_L_1 { get; set; }
        public double SIN_PLC_B14_TE_L_2 { get; set; }
        public double SIN_PLC_B14_TE_L_3 { get; set; }
        public double SIN_PLC_B14_TE_L_4 { get; set; }
        public double SIN_PLC_B14_TE_L_5 { get; set; }
        public double SIN_PLC_B14_TE_L_6 { get; set; }
        public double SIN_PLC_B15_TE_L_1 { get; set; }
        public double SIN_PLC_B15_TE_L_2 { get; set; }
        public double SIN_PLC_B15_TE_L_3 { get; set; }
        public double SIN_PLC_B15_TE_L_4 { get; set; }
        public double SIN_PLC_B15_TE_L_5 { get; set; }
        public double SIN_PLC_B15_TE_L_6 { get; set; }
        public double SIN_PLC_B16_TE_L_1 { get; set; }
        public double SIN_PLC_B16_TE_L_2 { get; set; }
        public double SIN_PLC_B16_TE_L_3 { get; set; }
        public double SIN_PLC_B16_TE_L_4 { get; set; }
        public double SIN_PLC_B16_TE_L_5 { get; set; }
        public double SIN_PLC_B16_TE_L_6 { get; set; }
        public double SIN_PLC_B17_TE_L_1 { get; set; }
        public double SIN_PLC_B17_TE_L_2 { get; set; }
        public double SIN_PLC_B17_TE_L_3 { get; set; }
        public double SIN_PLC_B17_TE_L_4 { get; set; }
        public double SIN_PLC_B17_TE_L_5 { get; set; }
        public double SIN_PLC_B17_TE_L_6 { get; set; }
        public double SIN_PLC_B18_TE_L_1 { get; set; }
        public double SIN_PLC_B18_TE_L_2 { get; set; }
        public double SIN_PLC_B18_TE_L_3 { get; set; }
        public double SIN_PLC_B18_TE_L_4 { get; set; }
        public double SIN_PLC_B18_TE_L_5 { get; set; }
        public double SIN_PLC_B18_TE_L_6 { get; set; }
        public double SIN_PLC_B19_TE_L_1 { get; set; }
        public double SIN_PLC_B19_TE_L_2 { get; set; }
        public double SIN_PLC_B19_TE_L_3 { get; set; }
        public double SIN_PLC_B19_TE_L_4 { get; set; }
        public double SIN_PLC_B19_TE_L_5 { get; set; }
        public double SIN_PLC_B19_TE_L_6 { get; set; }
        public double SIN_PLC_B20_TE_L_1 { get; set; }
        public double SIN_PLC_B20_TE_L_2 { get; set; }
        public double SIN_PLC_B20_TE_L_3 { get; set; }
        public double SIN_PLC_B20_TE_L_4 { get; set; }
        public double SIN_PLC_B20_TE_L_5 { get; set; }
        public double SIN_PLC_B20_TE_L_6 { get; set; }
        public double SIN_PLC_B21_TE_L_1 { get; set; }
        public double SIN_PLC_B21_TE_L_2 { get; set; }
        public double SIN_PLC_B21_TE_L_3 { get; set; }
        public double SIN_PLC_B21_TE_L_4 { get; set; }
        public double SIN_PLC_B21_TE_L_5 { get; set; }
        public double SIN_PLC_B21_TE_L_6 { get; set; }
        public double SIN_PLC_B22_TE_L_1 { get; set; }
        public double SIN_PLC_B22_TE_L_2 { get; set; }
        public double SIN_PLC_B22_TE_L_3 { get; set; }
        public double SIN_PLC_B22_TE_L_4 { get; set; }
        public double SIN_PLC_B22_TE_L_5 { get; set; }
        public double SIN_PLC_B22_TE_L_6 { get; set; }
        public double SIN_PLC_B23_TE_L_1 { get; set; }
        public double SIN_PLC_B23_TE_L_2 { get; set; }
        public double SIN_PLC_B23_TE_L_3 { get; set; }
        public double SIN_PLC_B23_TE_L_4 { get; set; }
        public double SIN_PLC_B23_TE_L_5 { get; set; }
        public double SIN_PLC_B23_TE_L_6 { get; set; }
        public double SIN_PLC_B01_PT_L { get; set; }
        public double SIN_PLC_B01_PT_R { get; set; }
        public double SIN_PLC_B02_PT_L { get; set; }
        public double SIN_PLC_B02_PT_R { get; set; }
        public double SIN_PLC_B03_PT_L { get; set; }
        public double SIN_PLC_B03_PT_R { get; set; }
        public double SIN_PLC_B04_PT_L { get; set; }
        public double SIN_PLC_B04_PT_R { get; set; }
        public double SIN_PLC_B05_PT_L { get; set; }
        public double SIN_PLC_B05_PT_R { get; set; }
        public double SIN_PLC_B06_PT_L { get; set; }
        public double SIN_PLC_B06_PT_R { get; set; }
        public double SIN_PLC_B07_PT_L { get; set; }
        public double SIN_PLC_B07_PT_R { get; set; }
        public double SIN_PLC_B08_PT_L { get; set; }
        public double SIN_PLC_B08_PT_R { get; set; }
        public double SIN_PLC_B09_PT_L { get; set; }
        public double SIN_PLC_B09_PT_R { get; set; }
        public double SIN_PLC_B10_PT_L { get; set; }
        public double SIN_PLC_B10_PT_R { get; set; }
        public double SIN_PLC_B11_PT_L { get; set; }
        public double SIN_PLC_B11_PT_R { get; set; }
        public double SIN_PLC_B12_PT_L { get; set; }
        public double SIN_PLC_B12_PT_R { get; set; }
        public double SIN_PLC_B13_PT_L { get; set; }
        public double SIN_PLC_B13_PT_R { get; set; }
        public double SIN_PLC_B14_PT_L { get; set; }
        public double SIN_PLC_B14_PT_R { get; set; }
        public double SIN_PLC_B15_PT_L { get; set; }
        public double SIN_PLC_B15_PT_R { get; set; }
        public double SIN_PLC_B16_PT_L { get; set; }
        public double SIN_PLC_B16_PT_R { get; set; }
        public double SIN_PLC_B17_PT_L { get; set; }
        public double SIN_PLC_B17_PT_R { get; set; }
        public double SIN_PLC_B18_PT_L { get; set; }
        public double SIN_PLC_B18_PT_R { get; set; }
        public double SIN_PLC_B19_PT_L { get; set; }
        public double SIN_PLC_B19_PT_R { get; set; }
        public double SIN_PLC_B20_PT_L { get; set; }
        public double SIN_PLC_B20_PT_R { get; set; }
        public double SIN_PLC_B21_PT_L { get; set; }
        public double SIN_PLC_B21_PT_R { get; set; }
        public double SIN_PLC_B22_PT_L { get; set; }
        public double SIN_PLC_B22_PT_R { get; set; }
        public double SIN_PLC_B23_PT_L { get; set; }
        public double SIN_PLC_B23_PT_R { get; set; }
        public double SIN_PLC_B01_ZT_L_SP { get; set; }
        public double SIN_PLC_B01_ZT_R_SP { get; set; }
        public double SIN_PLC_B02_ZT_L_SP { get; set; }
        public double SIN_PLC_B02_ZT_R_SP { get; set; }
        public double SIN_PLC_B03_ZT_L_SP { get; set; }
        public double SIN_PLC_B03_ZT_R_SP { get; set; }
        public double SIN_PLC_B04_ZT_L_SP { get; set; }
        public double SIN_PLC_B04_ZT_R_SP { get; set; }
        public double SIN_PLC_B05_ZT_L_SP { get; set; }
        public double SIN_PLC_B05_ZT_R_SP { get; set; }
        public double SIN_PLC_B06_ZT_L_SP { get; set; }
        public double SIN_PLC_B06_ZT_R_SP { get; set; }
        public double SIN_PLC_B07_ZT_L_SP { get; set; }
        public double SIN_PLC_B07_ZT_R_SP { get; set; }
        public double SIN_PLC_B08_ZT_L_SP { get; set; }
        public double SIN_PLC_B08_ZT_R_SP { get; set; }
        public double SIN_PLC_B09_ZT_L_SP { get; set; }
        public double SIN_PLC_B09_ZT_R_SP { get; set; }
        public double SIN_PLC_B10_ZT_L_SP { get; set; }
        public double SIN_PLC_B10_ZT_R_SP { get; set; }
        public double SIN_PLC_B11_ZT_L_SP { get; set; }
        public double SIN_PLC_B11_ZT_R_SP { get; set; }
        public double SIN_PLC_B12_ZT_L_SP { get; set; }
        public double SIN_PLC_B12_ZT_R_SP { get; set; }
        public double SIN_PLC_B13_ZT_L_SP { get; set; }
        public double SIN_PLC_B13_ZT_R_SP { get; set; }
        public double SIN_PLC_B14_ZT_L_SP { get; set; }
        public double SIN_PLC_B14_ZT_R_SP { get; set; }
        public double SIN_PLC_B15_ZT_L_SP { get; set; }
        public double SIN_PLC_B15_ZT_R_SP { get; set; }
        public double SIN_PLC_B16_ZT_L_SP { get; set; }
        public double SIN_PLC_B16_ZT_R_SP { get; set; }
        public double SIN_PLC_B17_ZT_L_SP { get; set; }
        public double SIN_PLC_B17_ZT_R_SP { get; set; }
        public double SIN_PLC_B18_ZT_L_SP { get; set; }
        public double SIN_PLC_B18_ZT_R_SP { get; set; }
        public double SIN_PLC_B19_ZT_L_SP { get; set; }
        public double SIN_PLC_B19_ZT_R_SP { get; set; }
        public double SIN_PLC_B20_ZT_L_SP { get; set; }
        public double SIN_PLC_B20_ZT_R_SP { get; set; }
        public double SIN_PLC_B21_ZT_L_SP { get; set; }
        public double SIN_PLC_B21_ZT_R_SP { get; set; }
        public double SIN_PLC_B22_ZT_L_SP { get; set; }
        public double SIN_PLC_B22_ZT_R_SP { get; set; }
        public double SIN_PLC_B23_ZT_L_SP { get; set; }
        public double SIN_PLC_B23_ZT_R_SP { get; set; }
        public double SIN_PLC_B01_ZT_L_PV { get; set; }
        public double SIN_PLC_B01_ZT_R_PV { get; set; }
        public double SIN_PLC_B02_ZT_L_PV { get; set; }
        public double SIN_PLC_B02_ZT_R_PV { get; set; }
        public double SIN_PLC_B03_ZT_L_PV { get; set; }
        public double SIN_PLC_B03_ZT_R_PV { get; set; }
        public double SIN_PLC_B04_ZT_L_PV { get; set; }
        public double SIN_PLC_B04_ZT_R_PV { get; set; }
        public double SIN_PLC_B05_ZT_L_PV { get; set; }
        public double SIN_PLC_B05_ZT_R_PV { get; set; }
        public double SIN_PLC_B06_ZT_L_PV { get; set; }
        public double SIN_PLC_B06_ZT_R_PV { get; set; }
        public double SIN_PLC_B07_ZT_L_PV { get; set; }
        public double SIN_PLC_B07_ZT_R_PV { get; set; }
        public double SIN_PLC_B08_ZT_L_PV { get; set; }
        public double SIN_PLC_B08_ZT_R_PV { get; set; }
        public double SIN_PLC_B09_ZT_L_PV { get; set; }
        public double SIN_PLC_B09_ZT_R_PV { get; set; }
        public double SIN_PLC_B10_ZT_L_PV { get; set; }
        public double SIN_PLC_B10_ZT_R_PV { get; set; }
        public double SIN_PLC_B11_ZT_L_PV { get; set; }
        public double SIN_PLC_B11_ZT_R_PV { get; set; }
        public double SIN_PLC_B12_ZT_L_PV { get; set; }
        public double SIN_PLC_B12_ZT_R_PV { get; set; }
        public double SIN_PLC_B13_ZT_L_PV { get; set; }
        public double SIN_PLC_B13_ZT_R_PV { get; set; }
        public double SIN_PLC_B14_ZT_L_PV { get; set; }
        public double SIN_PLC_B14_ZT_R_PV { get; set; }
        public double SIN_PLC_B15_ZT_L_PV { get; set; }
        public double SIN_PLC_B15_ZT_R_PV { get; set; }
        public double SIN_PLC_B16_ZT_L_PV { get; set; }
        public double SIN_PLC_B16_ZT_R_PV { get; set; }
        public double SIN_PLC_B17_ZT_L_PV { get; set; }
        public double SIN_PLC_B17_ZT_R_PV { get; set; }
        public double SIN_PLC_B18_ZT_L_PV { get; set; }
        public double SIN_PLC_B18_ZT_R_PV { get; set; }
        public double SIN_PLC_B19_ZT_L_PV { get; set; }
        public double SIN_PLC_B19_ZT_R_PV { get; set; }
        public double SIN_PLC_B20_ZT_L_PV { get; set; }
        public double SIN_PLC_B20_ZT_R_PV { get; set; }
        public double SIN_PLC_B21_ZT_L_PV { get; set; }
        public double SIN_PLC_B21_ZT_R_PV { get; set; }
        public double SIN_PLC_B22_ZT_L_PV { get; set; }
        public double SIN_PLC_B22_ZT_R_PV { get; set; }
        public double SIN_PLC_B23_ZT_L_PV { get; set; }
        public double SIN_PLC_B23_ZT_R_PV { get; set; }
        public int SIN_PLC_MA_FAN_1_SIGNAL { get; set; }
        public int SIN_PLC_MA_FAN_2_SIGNAL { get; set; }
        public double SIN_PLC_MA_FAN_1_SP { get; set; }
        public double SIN_PLC_MA_FAN_2_SP { get; set; }
        public double SIN_PLC_MA_FAN_1_PV { get; set; }
        public double SIN_PLC_MA_FAN_2_PV { get; set; }
        public int SIN_PLC_BTP_BUTTON { get; set; }
        public double SIN_PLC_MA_FAN_1_SP_OYT { get; set; }
        public double SIN_PLC_MA_FAN_2_SP_OUT { get; set; }
        public double SIN_PLC_MA_VE_1_SP_OD { get; set; }
        public double SIN_PLC_MA_VE_2_SP_OD { get; set; }
        public double SIN_PLC_MA_VE_1_PV_OD { get; set; }
        public double SIN_PLC_MA_VE_2_PV_OD { get; set; }
        public double SIN_PLC_MA_SB_1_FLUE_PT { get; set; }
        public double SIN_PLC_MA_SB_2_FLUE_PT { get; set; }
        public double SIN_PLC_MA_SB_1_FLUE_TE { get; set; }
        public double SIN_PLC_MA_SB_2_FLUE_TE { get; set; }
        public double SIN_PLC_MA_SB_1_FLUE_FT { get; set; }
        public double SIN_PLC_MA_SB_2_FLUE_FT { get; set; }
        public double SIN_PLC_MA_OUT_1_FLUE_PT { get; set; }
        public double SIN_PLC_MA_IN_1_FLUE_PT { get; set; }
        public double SIN_PLC_MA_OUT_1_FLUE_O2 { get; set; }
        public double SIN_PLC_MA_OUT_2_FLUE_PI { get; set; }
        public double SIN_PLC_MA_IN_2_FLUE_PI { get; set; }
        public double SIN_PLC_MA_OUT_2_FLUE_O2 { get; set; }
        public double SIN_PLC_MA_OUT_1_FLUE_DT { get; set; }
        public double SIN_PLC_MA_OUT_2_FLUE_DT { get; set; }
        public double SIN_PLC_MA_OUT_1_FLUE_TI { get; set; }
        public double SIN_PLC_MA_OUT_2_FLUE_TI { get; set; }
        public double SIN_PLC_MA_1_EC { get; set; }
        public double SIN_PLC_MA_2_EC { get; set; }
        public double SIN_PLC_MA_1_W { get; set; }
        public double SIN_PLC_MA_2_W { get; set; }
        public int SIN_PLC_FGD1_FAN_SIGNAL { get; set; }
        public int SIN_PLC_FGD2_FAN_SIGNAL { get; set; }
        public double SIN_PLC_FGD1_FAN_EC { get; set; }
        public double SIN_PLC_FGD2_FAN_EC { get; set; }
        public double SIN_PLC_FGD1_P1 { get; set; }
        public double SIN_PLC_FGD1_P2 { get; set; }
        public double SIN_PLC_FGD2_P1 { get; set; }
        public double SIN_PLC_FGD2_P2 { get; set; }
        public double SIN_PLC_FGD1_FLUE_W { get; set; }
        public double SIN_PLC_FGD2_FLUE_W { get; set; }
        public double SIN_PLC_FGD1_DP1 { get; set; }
        public double SIN_PLC_FGD1_DP2 { get; set; }
        public double SIN_PLC_FGD1_TI1 { get; set; }
        public double SIN_PLC_FGD1_TI2 { get; set; }
        public double SIN_PLC_FGD1_IN_TI { get; set; }
        public double SIN_PLC_FGD1_OUT_TI { get; set; }
        public double SIN_PLC_FGD1_IN_DT { get; set; }
        public double SIN_PLC_FGD1_OUT_DT { get; set; }
        public double SIN_PLC_FGD1_DT_DP { get; set; }
        public double SIN_PLC_FGD1_IN_SO2 { get; set; }
        public double SIN_PLC_FGD1_OUT_SO2 { get; set; }
        public double SIN_PLC_FGD1_IN_NO { get; set; }
        public double SIN_PLC_FGD1_OUT_NO { get; set; }
        public double SIN_PLC_FGD2_DP1 { get; set; }
        public double SIN_PLC_FGD2_DP2 { get; set; }
        public double SIN_PLC_FGD2_TI1 { get; set; }
        public double SIN_PLC_FGD2_TI2 { get; set; }
        public double SIN_PLC_FGD2_IN_TI { get; set; }
        public double SIN_PLC_FGD2_OUT_TI { get; set; }
        public double SIN_PLC_FGD2_IN_DT { get; set; }
        public double SIN_PLC_FGD2_OUT_DT { get; set; }
        public double SIN_PLC_FGD2_DT_DP { get; set; }
        public double SIN_PLC_FGD2_IN_SO2 { get; set; }
        public double SIN_PLC_FGD2_OUT_SO2 { get; set; }
        public double SIN_PLC_FGD2_IN_NO { get; set; }
        public double SIN_PLC_FGD2_OUT_NO { get; set; }
        public double SIN_PLC_FGD1_FAN_FQ { get; set; }
        public double SIN_PLC_FGD2_FAN_FQ { get; set; }
        public double SIN_PLC_FGD1_OUT_O2 { get; set; }
        public double SIN_PLC_FGD2_OUT_O2 { get; set; }
        public double SIN_PLC_LOOP_SK { get; set; }
        public double SIN_PLC_LOOP_SK_TI { get; set; }
        public double SIN_PLC_LOOP_SK_PI { get; set; }

    }
}
